name: Update CV PDF

on:
  push:
    paths:
      - "cv.md"  # Trigger only when cv.md changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert Markdown to PDF using Docker with full TeXLive
        run: docker run --rm -v ${{ github.workspace }}:/data blang/latex:ctanfull pandoc cv.md -o cv.pdf -V geometry:margin=1in,top=0.5in

      - name: List files
        run: ls -l

      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cv.pdf
          git commit -m "Update CV PDF" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
